[phases.setup]
nixPkgs = ['ffmpeg']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build completed"', 'which ffmpeg', 'ffmpeg -version']

[start]
cmd = 'python -m uvicorn main:app --host 0.0.0.0 --port $PORT'
